#dataset_root: /home/martinvalentine/Desktop/CSLR-VSL/data/processed/VSL_Sample/features/256x256px
dataset_root: ./dataset/VSL_V2
dict_path: ./preprocess/VSL_V2/gloss_dict.npy
evaluation_dir: ./evaluation/slr_eval
evaluation_prefix: vsl_v2-ground-truth